#---------------------------------------------------------------------------------------------------
#  _     ___    __
# | |__ /'v'\  / /   	\date        2022-01-14
# | / /(     )/ _ \   	\copyright   2021-2022 Sorbonne University
# |_\_\ x___x \___/                  https://opensource.org/licenses/MIT
#
#--------------------------------------------------------------------------------------------------

clean:
	make -C 1_hello_boot clean
	make -C 2_init_asm   clean
	make -C 3_init_c     clean
	make -C 4_nttys      clean
	make -C 5_driver     clean
